name: automatic image
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
         aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_KEY_ID }}
         aws-region: us-east-1
    - name: Install AWS CLI 
      run: |
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install --update
    - name: launch docker file
      env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
        USER_NAME : ${{ secrets.USER_NAME  }}
      run: |
        echo "############## Installing Docker ##############"
        sudo apt-get update -y
        sudo apt install unzip -y
        sudo apt install jq -y
        sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo apt-key fingerprint 0EBFCD88
        sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
        sudo apt-get update -y
        sudo apt-get install docker-ce docker-ce-cli containerd.io -y
        
        docker --version
        git clone https://github.com/AkshayDeqode/docekr_ecr.git
        cd ./docekr_ecr/
        docker build -t hello .

        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 844306356466.dkr.ecr.ap-south-1.amazonaws.com
        
        docker tag hello:latest 844306356466.dkr.ecr.ap-south-1.amazonaws.com/hello:latest
        docker push 844306356466.dkr.ecr.ap-south-1.amazonaws.com/hello:latest
